theme: jekyll-theme-minimal
title: Lyle Solomons
description: Im a third year Applications Development student obsessed with learning and pushing my limits
Click on the link below to view my Personal GitHub Profile
